# Give this service a name
spring.application.name=auth-service

# The auth service will run on port 9001
server.port=9001

# --- Eureka Client Configuration ---
eureka.client.service-url.defaultZone=${EUREKA_SERVICE_URL}
eureka.instance.prefer-ip-address=true

# --- Database Configuration ---
# We use the *same database* as the patient-service, but this service
# will manage its own tables (e.g., 'users').
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# --- JWT Configuration ---
# This secret key is used to sign and validate tokens.
# We'll put the real secret in the .env file.
jwt.secret=${JWT_SECRET}
# Token expiration time in milliseconds (e.g., 24 hours)
jwt.expiration=86400000