# Give this service a name
spring.application.name=discovery-service

# The port for the Eureka dashboard
server.port=8761

# --- Eureka Configuration ---
# This is a standalone server, so it should not try to register with itself.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Define the service URL
# 'discovery-service' here matches the container name we'll use in docker-compose
eureka.instance.hostname=discovery-service
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/