# Give this service a name
spring.application.name=billing-service

# The billing service will run on port 9002
server.port=9002

# --- Eureka Client Configuration ---
eureka.client.service-url.defaultZone=${EUREKA_SERVICE_URL}
eureka.instance.prefer-ip-address=true

# --- Database Configuration ---
# We use the *same database* as the patient-service
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update