# Give this service a name (must match folder)
spring.application.name=notifications-service

# The notifications service will run on port 9003
server.port=9003

# --- Eureka Client Configuration ---
eureka.client.service-url.defaultZone=${EUREKA_SERVICE_URL}
eureka.instance.prefer-ip-address=true